# -*- coding: utf-8 -*-

#
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(420, 150)
        SettingsDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appearanceGroupBox = QtWidgets.QGroupBox(SettingsDialog)
        self.appearanceGroupBox.setObjectName("appearanceGroupBox")
        self.appearanceLayout = QtWidgets.QGridLayout(self.appearanceGroupBox)
        self.appearanceLayout.setObjectName("appearanceLayout")
        self.colourSchemeLabel = QtWidgets.QLabel(self.appearanceGroupBox)
        self.colourSchemeLabel.setObjectName("colourSchemeLabel")
        self.appearanceLayout.addWidget(self.colourSchemeLabel, 0, 0, 1, 1)
        self.colourSchemeComboBox = QtWidgets.QComboBox(self.appearanceGroupBox)
        self.colourSchemeComboBox.setObjectName("colourSchemeComboBox")
        self.colourSchemeComboBox.addItem("")
        self.colourSchemeComboBox.addItem("")
        self.colourSchemeComboBox.addItem("")
        self.appearanceLayout.addWidget(self.colourSchemeComboBox, 0, 1, 1, 1)
        self.autosaveProjectCheckBox = QtWidgets.QCheckBox(self.appearanceGroupBox)
        self.autosaveProjectCheckBox.setObjectName("autosaveProjectCheckBox")
        self.appearanceLayout.addWidget(self.autosaveProjectCheckBox, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.appearanceGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.appearanceGroupBox.setTitle(_translate("SettingsDialog", "Appearance"))
        self.colourSchemeLabel.setText(_translate("SettingsDialog", "Colour scheme"))
        self.colourSchemeComboBox.setItemText(0, _translate("SettingsDialog", "System"))
        self.colourSchemeComboBox.setItemText(1, _translate("SettingsDialog", "Light"))
        self.colourSchemeComboBox.setItemText(2, _translate("SettingsDialog", "Dark"))
        self.autosaveProjectCheckBox.setText(_translate("SettingsDialog", "Autosave project changes for recovery"))
